/**
 * Customer quotes from Instagram / DMs. Segments with `pop: true` render bold in the marquee.
 */
export type MarqueeReviewPart = { t: string; pop?: boolean };

export type MarqueeReview = MarqueeReviewPart[];

export const MARQUEE_REVIEWS: MarqueeReview[] = [
  [
    { t: "Thank you soo much—I received it. " },
    { t: "Good is an understatement", pop: true },
    { t: "—it’s " },
    { t: "soo soo yummy", pop: true },
    { t: "." },
  ],
  [
    { t: "This is the " },
    { t: "best pancakes", pop: true },
    { t: " I have had—" },
    { t: "your hands are blessed", pop: true },
    { t: ", Masha Allah." },
  ],
  [
    { t: "Let me not disturb you but " },
    { t: "wallahi", pop: true },
    { t: " it is " },
    { t: "beautiful", pop: true },
    { t: ". " },
    { t: "Best", pop: true },
    { t: "." },
  ],
  [
    { t: "He ate " },
    { t: "almost all", pop: true },
    { t: ". My sister doesn’t eat pancake—" },
    { t: "but yours", pop: true },
    { t: "…" },
  ],
  [
    { t: "It tastes like a " },
    { t: "cake", pop: true },
    { t: ". " },
    { t: "Wallahi", pop: true },
    { t: "." },
  ],
  [
    { t: "CHEF KISS—it was " },
    { t: "so good", pop: true },
    { t: ". " },
    { t: "Perfect texture", pop: true },
    { t: ", not too sweet or too bland." },
  ],
  [
    { t: "I loved it " },
    { t: "sooo much", pop: true },
    { t: ", " },
    { t: "so so delicious", pop: true },
    { t: " " },
    { t: "wallahi", pop: true },
    { t: "—I’ve been talking about it " },
    { t: "nonstop", pop: true },
    { t: "." },
  ],
  [
    { t: "Allah ya kara ma kasuwa Albarka", pop: true },
    { t: "." },
  ],
  [
    { t: "This pancake can " },
    { t: "NEVER be over hyped", pop: true },
    { t: " " },
    { t: "wallahi", pop: true },
    { t: "!" },
  ],
  [
    { t: "Get yours—I promise a " },
    { t: "refund", pop: true },
    { t: " if you don’t like it." },
  ],
  [
    { t: "I can " },
    { t: "never say no", pop: true },
    { t: " to Batter and Bliss." },
  ],
  [
    { t: "Wallahi it’s " },
    { t: "sooooo niceeee", pop: true },
    { t: "—even after " },
    { t: "wahala", pop: true },
    { t: ", " },
    { t: "really niceeee", pop: true },
    { t: "." },
  ],
  [
    { t: "Worth the hype", pop: true },
    { t: ". After all those hours—still " },
    { t: "reallyy niceeee", pop: true },
    { t: ". " },
    { t: "Kaii masha Allah", pop: true },
    { t: "." },
  ],
  [
    { t: "Allah ya qaro kasuwa Mey albarka", pop: true },
    { t: ". Thank you sooo muchhh." },
  ],
  [
    { t: "Your pancakes were " },
    { t: "lovely", pop: true },
    { t: "—" },
    { t: "10/10", pop: true },
    { t: ". I " },
    { t: "loved it", pop: true },
    { t: ", " },
    { t: "mwahhh", pop: true },
    { t: "." },
  ],
  [
    { t: "I didn’t even know you did the " },
    { t: "pancakes", pop: true },
    { t: "." },
  ],
  [
    { t: "They were " },
    { t: "sooo nice", pop: true },
    { t: "—" },
    { t: "Allah", pop: true },
    { t: ", I’m " },
    { t: "definitely ordering again", pop: true },
    { t: "." },
  ],
  [
    { t: "Just finished the " },
    { t: "coconut milk", pop: true },
    { t: " " },
    { t: "nakaramasa", pop: true },
    { t: ". " },
    { t: "10/10", pop: true },
  ],
  [
    { t: "Your pancakes are " },
    { t: "so goodddddd", pop: true },
    { t: ", " },
    { t: "fluffyyy", pop: true },
    { t: "—and definitely " },
    { t: "worth the hype", pop: true },
    { t: "!!!" },
  ],
  [
    { t: "It " },
    { t: "melts in my mouth", pop: true },
    { t: " like ice cream." },
  ],
  [
    { t: "The coconut drink?? " },
    { t: "100/10", pop: true },
    { t: ". " },
    { t: "Creamy", pop: true },
    { t: " " },
    { t: "wallahi", pop: true },
    { t: ". Thank you so much." },
  ],
  [
    { t: "Thank you " },
    { t: "sooo sooo muchhhhhhhh", pop: true },
    { t: ". Omgggg I enjoyed " },
    { t: "everything single bite", pop: true },
    { t: "!" },
  ],
  [
    { t: "The " },
    { t: "coconut milk", pop: true },
    { t: " was " },
    { t: "just it", pop: true },
    { t: "!!!" },
  ],
  [
    { t: "Ya haduuuuu", pop: true },
    { t: ". Like " },
    { t: "sosaiiii", pop: true },
    { t: ". Thank you soo muchhhh." },
  ],
  [
    { t: "Can you stay in " },
    { t: "Kaduna", pop: true },
    { t: " forever?" },
  ],
  [
    { t: "Wannan coconut milk ai duniya ne", pop: true },
    { t: ". " },
    { t: "100/10", pop: true },
  ],
  [
    { t: "My brothers " },
    { t: "loved", pop: true },
    { t: " the " },
    { t: "tiger nut", pop: true },
    { t: "—they " },
    { t: "finished it", pop: true },
    { t: "." },
  ],
  [
    { t: "You got " },
    { t: "Batter", pop: true },
    { t: " and " },
    { t: "Bliss", pop: true },
    { t: " without me—I feel so " },
    { t: "betrayed", pop: true },
    { t: "." },
  ],
  [
    { t: "All the way from " },
    { t: "Abuja", pop: true },
    { t: " since Thursday." },
  ],
  [
    { t: "Wlhi it " },
    { t: "hits the spot", pop: true },
    { t: "—tastes like " },
    { t: "milkcake", pop: true },
    { t: ", " },
    { t: "not even pancake", pop: true },
    { t: ". " },
    { t: "Ampatutu", pop: true },
    { t: ", you no dey use " },
    { t: "juju", pop: true },
    { t: "?" },
  ],
  [
    { t: "I’m " },
    { t: "back again", pop: true },
    { t: "—" },
    { t: "I wanna order", pop: true },
    { t: " pleaseee!" },
  ],
  [
    { t: "You don’t tell people how " },
    { t: "good", pop: true },
    { t: " your " },
    { t: "pancakes", pop: true },
    { t: " are—from today " },
    { t: "I’ll be the one telling people", pop: true },
    { t: ". " },
    { t: "Whattttt", pop: true },
    { t: "." },
  ],
  [
    { t: "Love it so much—" },
    { t: "could eat this all day", pop: true },
    { t: "!" },
  ],
  [
    { t: "I must confess—it’s " },
    { t: "worth the hype", pop: true },
    { t: "." },
  ],
  [{ t: "Soo ", pop: true }, { t: "excited!!!", pop: true }],
  [
    { t: "I need " },
    { t: "14", pop: true },
    { t: " of this " },
    { t: "right now", pop: true },
    { t: "!!!" },
  ],
  [
    { t: "Wallahi yayi dadi", pop: true },
    { t: " · " },
    { t: "10/10", pop: true },
  ],
  [
    { t: "He told me he " },
    { t: "liked", pop: true },
    { t: " the " },
    { t: "coconut milk", pop: true },
    { t: " sef." },
  ],
  [
    { t: "The " },
    { t: "pancakes", pop: true },
    { t: " were " },
    { t: "really nice", pop: true },
    { t: ". " },
    { t: "I love it", pop: true },
    { t: "." },
  ],
  [
    { t: "I " },
    { t: "loved the pancakes", pop: true },
    { t: "! The " },
    { t: "coconut milk", pop: true },
    { t: " is " },
    { t: "very nice", pop: true },
    { t: " too." },
  ],
  [
    { t: "I received the pancakes—they were " },
    { t: "soo good", pop: true },
    { t: ", " },
    { t: "totally worth the hype", pop: true },
    { t: "." },
  ],
  [
    { t: "I got the pancakes! " },
    { t: "Your reviews really don’t lie", pop: true },
    { t: "—they " },
    { t: "taste really good", pop: true },
    { t: "." },
  ],
  [
    { t: "Omg it " },
    { t: "banged", pop: true },
    { t: ". The pancake was " },
    { t: "soooo soft", pop: true },
    { t: "." },
  ],
  [
    { t: "Honestly it was " },
    { t: "so nice", pop: true },
    { t: "—I " },
    { t: "enjoyed it sosaii", pop: true },
    { t: "." },
  ],
  [
    { t: "She never knew pancake could taste " },
    { t: "this good", pop: true },
    { t: "—it’s " },
    { t: "so fluffy", pop: true },
    { t: " and " },
    { t: "sweet", pop: true },
    { t: "." },
  ],
  [
    { t: "Thank you for " },
    { t: "saving my life", pop: true },
    { t: " and letting me try these." },
  ],
  [
    { t: "They’re " },
    { t: "worth the hype", pop: true },
    { t: "—or even needs more " },
    { t: "sefff", pop: true },
    { t: "." },
  ],
  [
    { t: "It literally " },
    { t: "melts in your mouth", pop: true },
    { t: ", " },
    { t: "abu kaman ice cream", pop: true },
    { t: "." },
  ],
  [
    { t: "The " },
    { t: "coconut milk", pop: true },
    { t: "—hard to explain " },
    { t: "how good", pop: true },
    { t: " it is." },
  ],
];
